[package]
name = "runctl"
version = "0.1.0"
edition = "2021"
authors = ["Muhammad Saheed <muhammad.saheed.iam@gmail.com>"]
description = "runctl - Simple and intuitive CLI for runit service management"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
